CREATE TABLE IF NOT EXISTS categories(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS products(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(50) NOT NULL,
    model varchar(50) DEFAULT NULL,
    sku varchar(50) DEFAULT NULL,
    price integer NOT NULL,
    description text,
    categoryId INTEGER REFERENCES categories(id)
);

